[package]
name = "soma_valores"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"] # cria uma lib compartilhada

[dependencies]
mlua = { version = "0.10", features = ["lua54", "module", "mlua_derive"]}
